/* System Package */
import { RefreshToken, RevokeReason } from '@prisma/client';
import { Result } from 'oxide.ts';

/**
 * Outcome of an attempted rotation.
 *
 * `NOT_CLAIMED` is not an error — it is the ordinary result of losing a race,
 * or of presenting a token that is already revoked or expired. The caller
 * diagnoses *which* of those it was by looking the row up and running the
 * grace/reuse decision; that split is deliberate, because only the losing path
 * needs the diagnosis and only the diagnosis knows whether to clear cookies.
 */
export type ClaimOutcome =
  | { outcome: 'CLAIMED'; parent: RefreshToken; child: RefreshToken }
  | { outcome: 'NOT_CLAIMED' };

export interface IssueRefreshTokenParams {
  userId: string;
  /** sha256 hex of the opaque token. The plaintext never reaches this layer. */
  tokenHash: string;
  familyId: string;
  expiresAt: Date;
}

export interface ClaimAndRotateParams {
  /** Hash of the token being presented. */
  tokenHash: string;
  /** Hash of its replacement. Generated by the caller — no crypto down here. */
  newTokenHash: string;
  newExpiresAt: Date;
  now: Date;
}

/**
 * Persistence for refresh-token families.
 *
 * Abstract class rather than an interface so it doubles as the Nest DI token,
 * matching `IAuthRepository`.
 */
export abstract class IRefreshTokenRepository {
  /** Starts a new family. Used by login and register. */
  abstract issue(
    params: IssueRefreshTokenParams,
  ): Promise<Result<RefreshToken, string>>;

  /**
   * Atomically revokes the presented token and issues its replacement in the
   * same family — or reports that it could not be claimed.
   *
   * Exactly one concurrent caller can ever succeed for a given hash.
   */
  abstract claimAndRotate(
    params: ClaimAndRotateParams,
  ): Promise<Result<ClaimOutcome, string>>;

  /**
   * Looks a row up by hash **including revoked ones**.
   *
   * Filtering on `revokedAt: null` here would be a security bug, not an
   * optimisation: a revoked row is exactly what reuse detection and logout
   * need to see. Without it a replayed stolen token reads as "unknown hash"
   * and its family is never killed.
   */
  abstract findByHash(
    tokenHash: string,
  ): Promise<Result<RefreshToken | null, string>>;

  /** Revokes every still-live row in a family. Returns how many were hit. */
  abstract revokeFamily(
    familyId: string,
    reason: RevokeReason,
    now: Date,
  ): Promise<Result<number, string>>;

  /**
   * Stamps `graceUsedAt` on a row, but only if it was still unset.
   *
   * Returns `false` when someone else got there first — the conditional write
   * is the mutex that makes "forgiven at most once" hold even when two losers
   * of the same race both read `graceUsedAt: null` and both decide grace.
   */
  abstract markGraceUsed(
    id: string,
    now: Date,
  ): Promise<Result<boolean, string>>;

  /**
   * Housekeeping: drops a user's rows that are past `expiresAt`.
   *
   * Deletes on expiry only, never on revocation. A revoked-but-unexpired row
   * has to survive, because deleting it would turn a detectable replay into an
   * unknown hash and silently disable reuse detection for that family.
   */
  abstract deleteExpiredForUser(
    userId: string,
    now: Date,
  ): Promise<Result<number, string>>;
}
